// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneCToOneCD.Models;

#nullable disable

namespace OneCToOneCD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250905030135_050925_4")]
    partial class _050925_4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OneCToOneCD.Models.Course", b =>
                {
                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseCode");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("OneCToOneCD.Models.CourseDetails", b =>
                {
                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseCode1")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInWeeks")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("CourseCode");

                    b.HasIndex("CourseCode1");

                    b.ToTable("CoursesDetails");
                });

            modelBuilder.Entity("OneCToOneCD.Models.Course", b =>
                {
                    b.HasOne("OneCToOneCD.Models.CourseDetails", "CourseDetails")
                        .WithOne()
                        .HasForeignKey("OneCToOneCD.Models.Course", "CourseCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourseDetails");
                });

            modelBuilder.Entity("OneCToOneCD.Models.CourseDetails", b =>
                {
                    b.HasOne("OneCToOneCD.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseCode1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });
#pragma warning restore 612, 618
        }
    }
}
